// Map module (seat map & booking)
const MAP_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vREyJWmMzv1p2obev-jTKdRsuCyhHKXy2mVGVMNICmYLkn9pOjpgmx0umxZ9rJYZqvPYEvqucp6VwJN/pub?output=csv";
const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwZSo-2MRZ-7QoXsQgFG32hew7aXSpgZmwjCP6FARkLcCrmyluw2L0ZZJsbc-H5fVRf/exec";

const BASE_X = -1128; const BASE_Y = 118; const BASE_Z = 827;
window.gridMatrix = window.gridMatrix || [];
window.csvOccupiedSeats = window.csvOccupiedSeats || {};
window.zoomLevel = 0.9;
window.selectedCell = null;
window.localCacheOccupied = JSON.parse(localStorage.getItem('NSCU_LOCAL_OCCUPIED_SEATS') || '{}');

async function loadMapData() {
    try {
        if (window.updateMapStatus) window.updateMapStatus(true, "遠端連線中...", "正在載入地圖空間...");
        const response = await fetch(MAP_CSV_URL);
        if (!response.ok) throw new Error("Connection failed");
        Papa.parse(await response.text(), { header: false, complete: function(results) { processCSVGrid(results.data); } });
    } catch (error) {
        if (window.updateMapStatus) window.updateMapStatus(false, "離線狀態", "⚠️ 雲端地圖載入失敗");
        const lo = document.getElementById('loadingOverlay'); if (lo) lo.classList.add('hidden');
    }
}

function updateMapStatus(isOnline, shortText, longText) { const statusMsg = document.getElementById('mapStatusMessage'); const statusText = document.getElementById('statusText'); if (statusMsg) statusMsg.textContent = longText; if (statusText) statusText.textContent = shortText; }

function processCSVGrid(rows) {
    window.csvOccupiedSeats = {}; window.gridMatrix = [];
    rows.slice(0, 77).forEach((row) => {
        const parsedRow = [];
        for (let c = 0; c < 52; c++) {
            let cellVal = (row[c] || '').trim();
            if (cellVal.includes('-')) {
                const parts = cellVal.split('-');
                window.csvOccupiedSeats[parts[0].trim()] = parts[1].trim();
                parsedRow.push(parts[0].trim());
            } else { parsedRow.push(cellVal); }
        }
        window.gridMatrix.push(parsedRow);
    });
    while (window.gridMatrix.length < 77) window.gridMatrix.push(Array(52).fill(""));
    if (window.cleanLocalCacheWithRemote) window.cleanLocalCacheWithRemote();
    const lo = document.getElementById('loadingOverlay'); if (lo) lo.classList.add('hidden');
    if (window.updateMapStatus) window.updateMapStatus(true, "同步成功", "9F 自習室實體地圖系統運作中");
    if (window.renderGridMap) window.renderGridMap(); if (window.calculateMapStatistics) window.calculateMapStatistics();
}

function cleanLocalCacheWithRemote() { let changed = false; Object.keys(window.localCacheOccupied || {}).forEach(seatId => { const cacheObj = window.localCacheOccupied[seatId]; const isRemoteOccupied = !!(window.csvOccupiedSeats || {})[seatId]; const remoteOwner = (window.csvOccupiedSeats || {})[seatId] || ""; if (cacheObj.status === 'occupied') { if (isRemoteOccupied && remoteOwner.toLowerCase() === cacheObj.name.toLowerCase()) { delete window.localCacheOccupied[seatId]; changed = true; } } else if (cacheObj.status === 'free') { if (!isRemoteOccupied) { delete window.localCacheOccupied[seatId]; changed = true; } } }); if (changed) localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); }

function checkSeatOccupied(seatId) { if (window.localCacheOccupied && window.localCacheOccupied[seatId]) { if (window.localCacheOccupied[seatId].status === 'occupied') return true; if (window.localCacheOccupied[seatId].status === 'free') return false; } return !!((window.csvOccupiedSeats || {})[seatId]); }

function calculateMapStatistics() { let totalSeats = 0; let availableA = 0; let availableB = 0; let occupied = 0; (window.gridMatrix || []).forEach(row => { row.forEach(cell => { if (!cell || cell === 'T' || cell === 'L') return; totalSeats++; const isOccupied = checkSeatOccupied(cell); if (isOccupied) { occupied++; } else { if (cell.startsWith('A')) availableA++; if (cell.startsWith('B')) availableB++; } }); }); const freeSeats = availableA + availableB; const rate = totalSeats > 0 ? ((occupied / totalSeats) * 100).toFixed(1) : '0.0'; const setText = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; }; setText('statTotal', totalSeats); setText('statTypeA', availableA); setText('statTypeB', availableB); setText('statOccupied', occupied); setText('statUsageRate', rate); const homeRate = document.getElementById('home-seat-rate'); const homeDesc = document.getElementById('home-seat-free-desc'); const lobbyFree = document.getElementById('lobby-free-seats'); if (homeRate) homeRate.innerText = rate; if (homeDesc) homeDesc.innerText = `餘位 ${freeSeats} 席・在線人數同步中`; if (lobbyFree) lobbyFree.innerText = freeSeats; if (window.checkMySeatStatus) window.checkMySeatStatus(); }

function checkMySeatStatus() { let mySeatId = "未登記"; if (window.ssoCurrentUser && window.ssoCurrentUser()) { const currentUser = window.ssoCurrentUser(); Object.keys(window.localCacheOccupied || {}).forEach(seatId => { if (window.localCacheOccupied[seatId].status === 'occupied' && window.localCacheOccupied[seatId].name.toLowerCase() === currentUser.username.toLowerCase()) { mySeatId = `9F - ${seatId}`; } }); } const seatBadge = document.getElementById('home-seat-badge'); if (seatBadge) seatBadge.innerText = mySeatId; }

function calculateLobbySeats() { const lobbyFree = document.getElementById('lobby-free-seats'); if (lobbyFree && (lobbyFree.innerText === '--' || lobbyFree.innerText === '0')) lobbyFree.innerText = "0"; }

function renderGridMap() {
    const container = document.getElementById('seatGridContainer'); if (!container) return; container.innerHTML = ''; container.style.gridTemplateColumns = `repeat(52, minmax(28px, 1fr))`; const fragment = document.createDocumentFragment(); (window.gridMatrix || []).forEach((row, rIndex) => { row.forEach((cell, cIndex) => { const blockX = BASE_X + cIndex; const blockY = BASE_Y; const blockZ = BASE_Z + rIndex; const cellEl = document.createElement('div'); cellEl.className = "grid-cell rounded-[3px] flex flex-col items-center justify-center text-[8px] font-bold select-none relative "; if (!cell) { cellEl.className += "bg-slate-100/10 border border-dashed border-slate-200/20 text-transparent"; } else if (cell === 'T') { cellEl.className += "bg-nscu-table border border-amber-950/40 cursor-default"; } else if (cell === 'L') { cellEl.className += "bg-nscu-lobby border border-black/40 cursor-default"; } else { cellEl.dataset.seatId = cell; cellEl.dataset.x = blockX; cellEl.dataset.y = blockY; cellEl.dataset.z = blockZ; const isOccupied = checkSeatOccupied(cell); let typeClass = ""; if (isOccupied) { typeClass = "bg-slate-200 border border-slate-300 text-slate-500 hover:bg-slate-300 cursor-pointer shadow-sm"; } else { if (cell.startsWith('A')) { typeClass = "bg-emerald-50 border border-emerald-300 text-emerald-800 hover:bg-emerald-100 hover:-translate-y-0.5 cursor-pointer shadow-sm"; } else if (cell.startsWith('B')) { typeClass = "bg-blue-50 border border-blue-300 text-blue-800 hover:bg-blue-100 hover:-translate-y-0.5 cursor-pointer shadow-sm"; } } cellEl.className += ` ${typeClass}`; cellEl.onclick = () => { if (window.openSeatModal) window.openSeatModal(cell, blockX, blockY, blockZ); }; cellEl.innerHTML = `<span class="scale-90 transform">${cell}</span>`; } fragment.appendChild(cellEl); }); }); container.appendChild(fragment); }

function highlightOnMap() { const query = (document.getElementById('mapSearch') || {}).value || ''; const q = query.toLowerCase().trim(); const cells = document.querySelectorAll('#seatGridContainer > .grid-cell'); cells.forEach(cell => { const seatId = cell.dataset.seatId; if (!seatId) { cell.style.opacity = q ? "0.1" : "1"; return; } if (!q) { cell.style.opacity = "1"; cell.style.filter = "none"; cell.style.transform = "none"; return; } if (seatId.toLowerCase().includes(q)) { cell.style.opacity = "1"; cell.style.filter = "drop-shadow(0 0 4px rgba(245, 158, 11, 0.9))"; cell.style.transform = "scale(1.15)"; cell.style.zIndex = "10"; } else { cell.style.opacity = "0.15"; cell.style.filter = "grayscale(80%)"; cell.style.transform = "none"; cell.style.zIndex = "1"; } }); }

function changeZoom(delta) { window.zoomLevel = Math.max(0.3, Math.min(1.8, (window.zoomLevel || 0.9) + delta)); const zp = document.getElementById('zoomPercent'); if (zp) zp.textContent = `${Math.round(window.zoomLevel * 100)}%`; const sg = document.getElementById('seatGridContainer'); if (sg) sg.style.transform = `scale(${window.zoomLevel})`; }

function openSeatModal(seatId, x, y, z) { if (window.guardAction) return window.guardAction(() => { window.selectedCell = { seatId, x, y, z }; const modal = document.getElementById('seatModal'); const container = document.getElementById('seatModalContainer'); const badge = document.getElementById('modalSeatBadge'); const title = document.getElementById('modalSeatId'); const statusText = document.getElementById('modalStatusText'); const headerBg = document.getElementById('modalHeaderBg'); const formSection = document.getElementById('formSection'); const detailsSection = document.getElementById('detailsSection'); if (formSection) formSection.classList.add('hidden'); if (detailsSection) detailsSection.classList.add('hidden'); if (window.toggleCancelForm) window.toggleCancelForm(false); if (title) title.textContent = `座位 ${seatId}`; const coords = document.getElementById('modalCoords'); if (coords) coords.textContent = `${x}, ${y}, ${z}`; const isOccupied = checkSeatOccupied(seatId); if (badge) { if (seatId.startsWith('A')) { badge.textContent = "一般單人席"; badge.className = "text-[9px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-white/10 border border-white/20"; } else { badge.textContent = "筆電禁用座位"; badge.className = "text-[9px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-blue-900/40 border border-blue-400/30 text-blue-100"; } } if (isOccupied) { if (headerBg) headerBg.className = "bg-gradient-to-r from-slate-600 to-slate-700 text-white p-5 relative"; if (statusText) statusText.innerHTML = '<i class="fa-solid fa-user-lock"></i> 座位已被使用 (隱私保護中)'; if (detailsSection) detailsSection.classList.remove('hidden'); const cancelInput = document.getElementById('cancelNameInput'); if (cancelInput && window.ssoCurrentUser) { const cu = window.ssoCurrentUser(); if (cu) { cancelInput.value = cu.username; cancelInput.disabled = true; } } } else { if (headerBg) headerBg.className = "bg-gradient-to-r from-nscu-green to-nscu-darkgreen text-white p-5 relative"; if (statusText) statusText.innerHTML = '<i class="fa-solid fa-circle-check text-emerald-300"></i> 空閒開放登記中'; if (formSection) formSection.classList.remove('hidden'); } if (modal) { modal.classList.remove('hidden'); setTimeout(() => { if (container) container.classList.replace('scale-95', 'scale-100'); }, 10); } if (window.lucide && window.lucide.createIcons) window.lucide.createIcons(); }); }

function closeSeatModal() { const modal = document.getElementById('seatModal'); const container = document.getElementById('seatModalContainer'); if (modal) modal.classList.replace('opacity-100', 'opacity-0'); if (container) container.classList.replace('scale-100', 'scale-95'); setTimeout(() => { if (modal) modal.classList.add('hidden'); window.selectedCell = null; }, 150); }

function toggleCancelForm(show) { const btn = document.getElementById('showCancelFormBtn'); const inputArea = document.getElementById('cancelFormInput'); if (show) { if (btn) btn.classList.add('hidden'); if (inputArea) inputArea.classList.remove('hidden'); } else { if (btn) btn.classList.remove('hidden'); if (inputArea) inputArea.classList.add('hidden'); } }

async function saveRegistration() { if (!window.selectedCell) return; const mcId = (document.getElementById('regName') || {}).value.trim(); if (!mcId) { if (window.showToast) window.showToast("⚠️ 請先登入您的 Minecraft 帳號！", "warning"); return; } window.localCacheOccupied[window.selectedCell.seatId] = { status: 'occupied', name: mcId, time: new Date().getTime() }; localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); if (window.showToast) window.showToast(`🎉 成功登記座位 ${window.selectedCell.seatId}！`); closeSeatModal(); if (window.renderGridMap) window.renderGridMap(); if (window.calculateMapStatistics) window.calculateMapStatistics(); try { fetch(APPS_SCRIPT_URL, { method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'text/plain' }, body: JSON.stringify({ seatId: window.selectedCell.seatId, minecraftId: mcId, action: 'register' }) }); } catch (e) {} }

async function confirmCancelRegistration() { if (!window.selectedCell) return; const inputMcId = (document.getElementById('cancelNameInput') || {}).value.trim(); if (!inputMcId) { if (window.showToast) window.showToast("⚠️ 驗證玩家身分失敗！", "warning"); return; } const currentOccupant = window.getSeatOccupantName ? window.getSeatOccupantName(window.selectedCell.seatId) : null; if (!window.ssoCurrentUser || window.ssoCurrentUser().username.toLowerCase() !== inputMcId.toLowerCase() || (currentOccupant && currentOccupant.toLowerCase() !== window.ssoCurrentUser().username.toLowerCase())) { if (window.showToast) window.showToast("❌ 身分驗證失敗！您無權限退還此座位。", "error"); return; } window.localCacheOccupied[window.selectedCell.seatId] = { status: 'free', name: '', time: new Date().getTime() }; localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); if (window.showToast) window.showToast(`🧹 座位 ${window.selectedCell.seatId} 已恢復空閒。`); closeSeatModal(); if (window.renderGridMap) window.renderGridMap(); if (window.calculateMapStatistics) window.calculateMapStatistics(); try { fetch(`${APPS_SCRIPT_URL}?action=cancel&seatId=${encodeURIComponent(window.selectedCell.seatId)}&minecraftId=${encodeURIComponent(inputMcId)}`); } catch (e) {} }

function copyMinecraftAction(type) { if (!window.selectedCell) return; const { x, y, z } = window.selectedCell; const textToCopy = type === 'tp' ? `/tp @s ${x} ${y} ${z}` : `${x} ${y} ${z}`; navigator.clipboard.writeText(textToCopy).then(() => { if (window.showToast) window.showToast(`📋 已複製：${textToCopy}`); }); }

Object.assign(window, { loadMapData, updateMapStatus, processCSVGrid, cleanLocalCacheWithRemote, checkSeatOccupied, calculateMapStatistics, checkMySeatStatus, calculateLobbySeats, renderGridMap, highlightOnMap, changeZoom, openSeatModal, closeSeatModal, toggleCancelForm, saveRegistration, confirmCancelRegistration, copyMinecraftAction, gridMatrix: window.gridMatrix, csvOccupiedSeats: window.csvOccupiedSeats });
// Map & booking module
const MAP_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vREyJWmMzv1p2obev-jTKdRsuCyhHKXy2mVGVMNICmYLkn9pOjpgmx0umxZ9rJYZqvPYEvqucp6VwJN/pub?output=csv";
const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwZSo-2MRZ-7QoXsQgFG32hew7aXSpgZmwjCP6FARkLcCrmyluw2L0ZZJsbc-H5fVRf/exec";

const BASE_X = -1128; const BASE_Y = 118; const BASE_Z = 827;
window.gridMatrix = window.gridMatrix || [];
window.csvOccupiedSeats = {};
window.zoomLevel = window.zoomLevel || 0.9;
window.selectedCell = null;
window.localCacheOccupied = JSON.parse(localStorage.getItem('NSCU_LOCAL_OCCUPIED_SEATS') || '{}');

async function loadMapData() {
    try {
        updateMapStatus(true, "遠端連線中...", "正在載入地圖空間...");
        const response = await fetch(MAP_CSV_URL);
        if (!response.ok) throw new Error("Connection failed");
        Papa.parse(await response.text(), { header: false, complete: function(results) { processCSVGrid(results.data); } });
    } catch (error) { updateMapStatus(false, "離線狀態", "⚠️ 雲端地圖載入失敗"); const lo = document.getElementById('loadingOverlay'); if (lo) lo.classList.add('hidden'); }
}
function updateMapStatus(isOnline, shortText, longText) { const statusMsg = document.getElementById('mapStatusMessage'); const statusText = document.getElementById('statusText'); if (statusMsg) statusMsg.textContent = longText; if (statusText) statusText.textContent = shortText; }
function processCSVGrid(rows) { window.csvOccupiedSeats = {}; window.gridMatrix = []; rows.slice(0, 77).forEach((row) => { const parsedRow = []; for (let c = 0; c < 52; c++) { let cellVal = (row[c] || '').trim(); if (cellVal.includes('-')) { const parts = cellVal.split('-'); window.csvOccupiedSeats[parts[0].trim()] = parts[1].trim(); parsedRow.push(parts[0].trim()); } else { parsedRow.push(cellVal); } } window.gridMatrix.push(parsedRow); }); while (window.gridMatrix.length < 77) window.gridMatrix.push(Array(52).fill("")); cleanLocalCacheWithRemote(); const lo = document.getElementById('loadingOverlay'); if (lo) lo.classList.add('hidden'); updateMapStatus(true, "同步成功", "9F 自習室實體地圖系統運作中"); renderGridMap(); calculateMapStatistics(); }
function cleanLocalCacheWithRemote() { let changed = false; Object.keys(window.localCacheOccupied).forEach(seatId => { const cacheObj = window.localCacheOccupied[seatId]; const isRemoteOccupied = !!window.csvOccupiedSeats[seatId]; const remoteOwner = window.csvOccupiedSeats[seatId] || ""; if (cacheObj.status === 'occupied') { if (isRemoteOccupied && remoteOwner.toLowerCase() === cacheObj.name.toLowerCase()) { delete window.localCacheOccupied[seatId]; changed = true; } } else if (cacheObj.status === 'free') { if (!isRemoteOccupied) { delete window.localCacheOccupied[seatId]; changed = true; } } }); if (changed) localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); }
function checkSeatOccupied(seatId) { if (window.localCacheOccupied[seatId]) { if (window.localCacheOccupied[seatId].status === 'occupied') return true; if (window.localCacheOccupied[seatId].status === 'free') return false; } return !!window.csvOccupiedSeats[seatId]; }
function calculateMapStatistics() { let totalSeats = 0; let availableA = 0; let availableB = 0; let occupied = 0; window.gridMatrix.forEach(row => { row.forEach(cell => { if (!cell || cell === 'T' || cell === 'L') return; totalSeats++; const isOccupied = checkSeatOccupied(cell); if (isOccupied) { occupied++; } else { if (cell.startsWith('A')) availableA++; if (cell.startsWith('B')) availableB++; } }); }); const freeSeats = availableA + availableB; const rate = totalSeats > 0 ? ((occupied / totalSeats) * 100).toFixed(1) : '0.0'; const setText = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; }; setText('statTotal', totalSeats); setText('statTypeA', availableA); setText('statTypeB', availableB); setText('statOccupied', occupied); setText('statUsageRate', rate); const homeRate = document.getElementById('home-seat-rate'); const homeDesc = document.getElementById('home-seat-free-desc'); const lobbyFree = document.getElementById('lobby-free-seats'); if (homeRate) homeRate.innerText = rate; if (homeDesc) homeDesc.innerText = `餘位 ${freeSeats} 席・在線人數同步中`; if (lobbyFree) lobbyFree.innerText = freeSeats; if (window.checkMySeatStatus) window.checkMySeatStatus(); }
function checkMySeatStatus() { let mySeatId = "未登記"; if (window.ssoCurrentUser && window.ssoCurrentUser()) { Object.keys(window.localCacheOccupied).forEach(seatId => { if (window.localCacheOccupied[seatId].status === 'occupied' && window.localCacheOccupied[seatId].name.toLowerCase() === window.ssoCurrentUser().username.toLowerCase()) { mySeatId = `9F - ${seatId}`; } }); } const seatBadge = document.getElementById('home-seat-badge'); if (seatBadge) seatBadge.innerText = mySeatId; }
function calculateLobbySeats() { const lobbyFree = document.getElementById('lobby-free-seats'); if (lobbyFree && (lobbyFree.innerText === '--' || lobbyFree.innerText === '0')) lobbyFree.innerText = "0"; }
function renderGridMap() { const container = document.getElementById('seatGridContainer'); if (!container) return; container.innerHTML = ''; container.style.gridTemplateColumns = `repeat(52, minmax(28px, 1fr))`; const fragment = document.createDocumentFragment(); window.gridMatrix.forEach((row, rIndex) => { row.forEach((cell, cIndex) => { const blockX = BASE_X + cIndex; const blockY = BASE_Y; const blockZ = BASE_Z + rIndex; const cellEl = document.createElement('div'); cellEl.className = "grid-cell rounded-[3px] flex flex-col items-center justify-center text-[8px] font-bold select-none relative "; if (!cell) { cellEl.className += "bg-slate-100/10 border border-dashed border-slate-200/20 text-transparent"; } else if (cell === 'T') { cellEl.className += "bg-nscu-table border border-amber-950/40 cursor-default"; } else if (cell === 'L') { cellEl.className += "bg-nscu-lobby border border-black/40 cursor-default"; } else { cellEl.dataset.seatId = cell; cellEl.dataset.x = blockX; cellEl.dataset.y = blockY; cellEl.dataset.z = blockZ; const isOccupied = checkSeatOccupied(cell); let typeClass = ""; if (isOccupied) { typeClass = "bg-slate-200 border border-slate-300 text-slate-500 hover:bg-slate-300 cursor-pointer shadow-sm"; } else { if (cell.startsWith('A')) { typeClass = "bg-emerald-50 border border-emerald-300 text-emerald-800 hover:bg-emerald-100 hover:-translate-y-0.5 cursor-pointer shadow-sm"; } else if (cell.startsWith('B')) { typeClass = "bg-blue-50 border border-blue-300 text-blue-800 hover:bg-blue-100 hover:-translate-y-0.5 cursor-pointer shadow-sm"; } } cellEl.className += ` ${typeClass}`; cellEl.onclick = () => { if (window.openSeatModal) window.openSeatModal(cell, blockX, blockY, blockZ); }; cellEl.innerHTML = `<span class="scale-90 transform">${cell}</span>`; } fragment.appendChild(cellEl); }); }); container.appendChild(fragment); }
function highlightOnMap() { const query = (document.getElementById('mapSearch') || {}).value.toLowerCase().trim(); const cells = document.querySelectorAll('#seatGridContainer > .grid-cell'); cells.forEach(cell => { const seatId = cell.dataset.seatId; if (!seatId) { cell.style.opacity = query ? "0.1" : "1"; return; } if (!query) { cell.style.opacity = "1"; cell.style.filter = "none"; cell.style.transform = "none"; return; } if (seatId.toLowerCase().includes(query)) { cell.style.opacity = "1"; cell.style.filter = "drop-shadow(0 0 4px rgba(245, 158, 11, 0.9))"; cell.style.transform = "scale(1.15)"; cell.style.zIndex = "10"; } else { cell.style.opacity = "0.15"; cell.style.filter = "grayscale(80%)"; cell.style.transform = "none"; cell.style.zIndex = "1"; } }); }
function changeZoom(delta) { window.zoomLevel = Math.max(0.3, Math.min(1.8, window.zoomLevel + delta)); const zp = document.getElementById('zoomPercent'); if (zp) zp.textContent = `${Math.round(window.zoomLevel * 100)}%`; const sg = document.getElementById('seatGridContainer'); if (sg) sg.style.transform = `scale(${window.zoomLevel})`; }
function openSeatModal(seatId, x, y, z) { if (window.guardAction) return window.guardAction(() => { window.selectedCell = { seatId, x, y, z }; const modal = document.getElementById('seatModal'); const container = document.getElementById('seatModalContainer'); const badge = document.getElementById('modalSeatBadge'); const title = document.getElementById('modalSeatId'); const statusText = document.getElementById('modalStatusText'); const headerBg = document.getElementById('modalHeaderBg'); const formSection = document.getElementById('formSection'); const detailsSection = document.getElementById('detailsSection'); if (formSection) formSection.classList.add('hidden'); if (detailsSection) detailsSection.classList.add('hidden'); if (window.toggleCancelForm) window.toggleCancelForm(false); if (title) title.textContent = `座位 ${seatId}`; const coords = document.getElementById('modalCoords'); if (coords) coords.textContent = `${x}, ${y}, ${z}`; const isOccupied = checkSeatOccupied(seatId); if (badge) { if (seatId.startsWith('A')) { badge.textContent = "一般單人席"; badge.className = "text-[9px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-white/10 border border-white/20"; } else { badge.textContent = "筆電禁用座位"; badge.className = "text-[9px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-blue-900/40 border border-blue-400/30 text-blue-100"; } } if (isOccupied) { if (headerBg) headerBg.className = "bg-gradient-to-r from-slate-600 to-slate-700 text-white p-5 relative"; if (statusText) statusText.innerHTML = '<i class="fa-solid fa-user-lock"></i> 座位已被使用 (隱私保護中)'; if (detailsSection) detailsSection.classList.remove('hidden'); const cancelInput = document.getElementById('cancelNameInput'); if (cancelInput && window.ssoCurrentUser) { const cu = window.ssoCurrentUser(); if (cu) { cancelInput.value = cu.username; cancelInput.disabled = true; } } } else { if (headerBg) headerBg.className = "bg-gradient-to-r from-nscu-green to-nscu-darkgreen text-white p-5 relative"; if (statusText) statusText.innerHTML = '<i class="fa-solid fa-circle-check text-emerald-300"></i> 空閒開放登記中'; if (formSection) formSection.classList.remove('hidden'); } if (modal) { modal.classList.remove('hidden'); setTimeout(() => container.classList.replace('scale-95', 'scale-100'), 10); } }); }
function closeSeatModal() { const modal = document.getElementById('seatModal'); const container = document.getElementById('seatModalContainer'); if (modal) modal.classList.replace('opacity-100', 'opacity-0'); if (container) container.classList.replace('scale-100', 'scale-95'); setTimeout(() => { if (modal) modal.classList.add('hidden'); window.selectedCell = null; }, 150); }
function toggleCancelForm(show) { const btn = document.getElementById('showCancelFormBtn'); const inputArea = document.getElementById('cancelFormInput'); if (show) { if (btn) btn.classList.add('hidden'); if (inputArea) inputArea.classList.remove('hidden'); } else { if (btn) btn.classList.remove('hidden'); if (inputArea) inputArea.classList.add('hidden'); } }
async function saveRegistration() { if (!window.selectedCell) return; const mcId = document.getElementById('regName').value.trim(); if (!mcId) { if (window.showToast) window.showToast("⚠️ 請先登入您的 Minecraft 帳號！", "warning"); return; } window.localCacheOccupied[window.selectedCell.seatId] = { status: 'occupied', name: mcId, time: new Date().getTime() }; localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); if (window.showToast) window.showToast(`🎉 成功登記座位 ${window.selectedCell.seatId}！`); closeSeatModal(); renderGridMap(); calculateMapStatistics(); try { fetch(APPS_SCRIPT_URL, { method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'text/plain' }, body: JSON.stringify({ seatId: window.selectedCell.seatId, minecraftId: mcId, action: 'register' }) }); } catch (e) {} }
async function confirmCancelRegistration() { if (!window.selectedCell) return; const inputMcId = document.getElementById('cancelNameInput').value.trim(); if (!inputMcId) { if (window.showToast) window.showToast("⚠️ 驗證玩家身分失敗！", "warning"); return; } const currentOccupant = window.getSeatOccupantName ? window.getSeatOccupantName(window.selectedCell.seatId) : null; if (!window.ssoCurrentUser || window.ssoCurrentUser().username.toLowerCase() !== inputMcId.toLowerCase() || (currentOccupant && currentOccupant.toLowerCase() !== window.ssoCurrentUser().username.toLowerCase())) { if (window.showToast) window.showToast("❌ 身分驗證失敗！您無權限退還此座位。", "error"); return; } window.localCacheOccupied[window.selectedCell.seatId] = { status: 'free', name: '', time: new Date().getTime() }; localStorage.setItem('NSCU_LOCAL_OCCUPIED_SEATS', JSON.stringify(window.localCacheOccupied)); if (window.showToast) window.showToast(`🧹 座位 ${window.selectedCell.seatId} 已恢復空閒。`); closeSeatModal(); renderGridMap(); calculateMapStatistics(); try { fetch(`${APPS_SCRIPT_URL}?action=cancel&seatId=${encodeURIComponent(window.selectedCell.seatId)}&minecraftId=${encodeURIComponent(inputMcId)}`); } catch (e) {} }
function copyMinecraftAction(type) { if (!window.selectedCell) return; const { x, y, z } = window.selectedCell; const textToCopy = type === 'tp' ? `/tp @s ${x} ${y} ${z}` : `${x} ${y} ${z}`; navigator.clipboard.writeText(textToCopy).then(() => { if (window.showToast) window.showToast(`📋 已複製：${textToCopy}`); }); }

Object.assign(window, { loadMapData, processCSVGrid, renderGridMap, calculateMapStatistics, checkSeatOccupied, openSeatModal, closeSeatModal, saveRegistration, confirmCancelRegistration, copyMinecraftAction, toggleCancelForm, changeZoom, highlightOnMap, calculateLobbySeats, checkMySeatStatus });
